name: JG SDK CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See issue #507 of actions/setup-go for the reason why we are wrapping the version in single quotation marks.
        go-version: [ '1.16', '1.17', '1.18', '1.19', '1.20', '1.21', '1.22', '1.23', '1.24' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Modify go.mod to use Go ${{ matrix.go-version }}
        run: go mod edit -go=${{ matrix.go-version }}

      - name: Build the code (for go compatibility check)
        run: go build ./...

      - name: Run tests (if any)
        run: go test ./...